version: "3"

networks:
  bnp-app-network:

services:

  # nginx
  nginx-service:
    image: nginx:stable-alpine
    container_name: nginx-container
    ports:
      - "8090:80"
    volumes:
      - ./bnp-app:/var/www/bnp-app
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php74-service
    networks:
      - bnp-app-network

  # php
  php74-service:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    container_name: php74-container
    ports:
      - "9000:9000"
    volumes:
      - ./bnp-app:/var/www/bnp-app
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    networks:
      - bnp-app-network


