version: "3.8"

networks:
  docker-network:

services:

  # php 7.4
  app-service:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    image: bnp-app-image
    container_name: bnp-app-container
    ports:
      - "9000:9000"
    volumes:
      - .:/var/www/bnp-zenica.com
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    networks:
      - docker-network

  # nginx
  nginx-service:
    image: nginx:stable-alpine
    container_name: bnp-nginx-container
    ports:
      - "8090:80"
    volumes:
      - .:/var/www/bnp-zenica.com
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app-service
    networks:
      - docker-network

