# Hyprland config file

# load colors created by: wal -q -i "/path/to/wallpaper"
source= ~/.cache/wal/colors-hyprland.conf

#-------------------------------------------------------------------------
# MONITORS
#-------------------------------------------------------------------------
source = ~/MyHyprland/config/hypr/conf/monitor.conf

#-------------------------------------------------------------------------
# AUTOSTART - NOT DONE !!!!!!!!!!!!!
#-------------------------------------------------------------------------
source = ~/MyHyprland/config/hypr/conf/autostart.conf

#-------------------------------------------------------------------------
# KEYBINDINGS and DEFAULT PROGRAMS
#-------------------------------------------------------------------------
source = ~/MyHyprland/config/hypr/conf/keybindings.conf

#-------------------------------------------------------------------------
# CURSORS
#-------------------------------------------------------------------------
exec-once = hyprctl setcursor Adwaita 24

#-------------------------------------------------------------------------
# ENVIRONMENT VARIABLES
#-------------------------------------------------------------------------
source = ~/MyHyprland/config/hypr/conf/env.conf

#-------------------------------------------------------------------------
# KEYBOARD
#-------------------------------------------------------------------------
source = ~/MyHyprland/config/hypr/conf/keyboard.conf

#----------------------------------------------------- 
# COLORS - NOT DONE
#----------------------------------------------------- 
# source = ~/.cache/wal/colors-hyprland.conf

#-------------------------------------------------------------------------
# WINDOWS DESIGN (gaps, borders, blur)
#-------------------------------------------------------------------------
source = ~/MyHyprland/config/hypr/conf/windows.conf

#-------------------------------------------------------------------------
# LAYOUT
#-------------------------------------------------------------------------
source = ~/MyHyprland/config/hypr/conf/layout.conf

#-------------------------------------------------------------------------
# MISC
#-------------------------------------------------------------------------
source = ~/MyHyprland/config/hypr/conf/misc.conf

#-------------------------------------------------------------------------
# WINDOWRULES
#-------------------------------------------------------------------------
source = ~/MyHyprland/config/hypr/conf/windowrules.conf

#-------------------------------------------------------------------------
# ANIMATIONS
#-------------------------------------------------------------------------
source = ~/MyHyprland/config/hypr/conf/animations.conf

#-------------------------------------------------------------------------
# CUSTOM (last loaded config file for overrides)
#-------------------------------------------------------------------------
source = ~/MyHyprland/config/hypr/conf/custom.conf

# ----------------------------------------------------- 
# Environment for xdg-desktop-portal-hyprland
# ----------------------------------------------------- 
exec-once=dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP


