# Add your additional Hyprland configurations here
# 
# This is an additional key binding 
# bind = $mainMod CTRL, up, workspace, empty
bind = $mainMod, R, exec, rofi -show drun -replace -i
bind = ALT, SPACE, exec, rofi -show drun -replace -i
bind = , XF86MonBrightnessUp, exec, brightnessctl s +5%
bind = , XF86MonBrightnessDown, exec, brightnessctl s 5%-
# 
# Example for xwayland
# xwayland {
#   force_zero_scaling = true
# }

# qt5ct environment variable
# env = QT_QPA_PLATFORMTHEME,qt5ct

# Start Nextcloud Desktop Client
# exec-once = /usr/bin/nextcloud --background

# see: hyprctl clients
windowrule = workspace 9, ^(.*thunderbird.*)$
#exec-once = [workspace 4 silent] thunderbird