# ----------------------------------------------------- 
# Monitor Setup
# name: "Dell U2412M"
# ----------------------------------------------------- 
monitor=DP-1, 1920x1200, auto, 1
monitor=HDMI-A-1, disable
