# Add your additional Hyprland configurations here

# see: hyprctl clients
windowrule = workspace 5, ^(.*Chromium.*)$
windowrule = workspace 9, ^(.*thunderbird.*)$
#exec-once = [workspace 4 silent] thunderbird
