# ----------------------------------------------------- 
# Monitor Setup
# name: "Lenovo ThinkVision"
# ----------------------------------------------------- 
monitor=HDMI-A-1, 1920x1080, auto, 1
monitor=DP-1, disable
