[Greeter]
background=/usr/share/backgrounds/login/photo-1711349478322-d660394c45b4.jpg
theme-name=Mint-Y-Dark-Blue
icon-theme-name=MacTahoe
cursor-theme-name=Adwaita
show-a11y=false
draw-user-backgrounds=true
